//home strings
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
//home screen strings
const searchanything = "Search anything...",
    todayDeal = "Today's Deal",
    flashsale = "Flash Sale",
    topBrand = "Top Brand",
    topSellers = "Top Sellers",
    topCategories = "Top Categories",
    womenDress = "Women Dress",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysDress = "Boys Dress",
    boysGlasses = "Boys Glasses",
    tshorts = "Tshorts",
    kidsDress = "Kids Dress",
    girlssac = "Girls Sac",
    girlsDress = "Girls Dress",
    electroniques = "Electronique",
    featureCategories = "Featured Categories";


const login="Login",
    email="Email",
    welcome ="Welcom to seller shope",
    loginTo =" Login to your account",
    password="Password",
    logout = "Logout",
    forgetPassword="Forget Password ?",
    anyProblem="In case of any difficulty, contact administration",
    emailHint="your.email@gmail.com",
    passwordHint="* * * * * *",
    dashboard = "Dashboard",
    orders= "Orders",
    products = "Products",
    settings= "Settings",
    rating= "Rating",
    unpaid = "Unpaid",
    featured = "Featured",
    edit = "Edit",
    remove = "Remove",
    save = "Save",
    editProfile = "Edit Profile",
    totalSales = "Total Sales",
    popular = "Popular Products",
    messages = "Messages",
    changeImage = "Change Image",
    shopSettings = "Shop Settings",
    name= "Username",
    chats = "Chats",
    confirmPassword = "Confirm Password",
    credit="@teamsProject";

//shop settings strings
const nameHint = "ex: Vendor Name",
  shopDescHint = "Enter your shop description",
  shopMobileHint = "ex:+212625255896",
  shopWebsiteHint = "ex:vendor.shop.com",
  shopAddressHint= "ex:Rue Hay Riyad",
  description = "Desscription", 
  mobile = "Shop Mobile" , 
  website = "shop Website", 
  shopname = "Shop Name ",
  adress = "Shop Adress" ;

